import { GeneratedPlan } from "./InteractiveApp";

export const recalibrationSchedule = [
  {
    time: "05:30",
    label: "WAKE ANCHOR",
    icon: "☀️",
    duration: "15 min",
    category: "mindset",
    title: "Morning Stillness Protocol",
    description: "No phone. Sit up immediately. Drink 16oz of water. Spend 5 minutes breathing.",
    why: "Breaking the cortisol spike from instantly checking notifications. Anchors you to intention before noise.",
    triathlete: false,
    founder: false,
    recovery: true,
    baseChecks: ["Put phone face-down before sleeping", "Set water bottle by bed tonight", "Sit up within 3 seconds of waking"]
  },
  {
    time: "05:45",
    label: "VISION WRITE",
    icon: "📓",
    duration: "15 min",
    category: "purpose",
    title: "3-Pillar Journal Entry",
    description: "Write 3 short entries — one sentence minimum each:\n1. ATHLETE: 'My Olympic physical ceiling is...'\n2. FOUNDER: 'The sovereign product I am shipping...'\n3. HUMAN: 'I am grounding today in...'",
    why: "You are not just an employee. You have two sovereign projects and an identity outside standard labor.",
    triathlete: true,
    founder: true,
    recovery: false,
    baseChecks: ["Write ATHLETE sentence", "Write FOUNDER sentence", "Write HUMAN sentence"]
  },
  {
    time: "06:00",
    label: "TRAIN",
    icon: "🏊",
    duration: "75 min",
    category: "triathlon",
    title: "Triathlon Training Block",
    description: "Rotating weekly focus:\n• Mon/Thu: Swim (technique + intervals)\n• Tue/Fri: Bike (sweet spot intervals)\n• Wed/Sat: Run (zone 2 aerobic base)",
    why: "Morning training is non-negotiable because evenings get eaten by exhaustion. Zone 2 aerobic engine protects cognitive stamina.",
    triathlete: true,
    founder: false,
    recovery: true,
    baseChecks: ["Gear laid out the night before", "Complete training session", "Stay in Zone 2 during training base"]
  },
  {
    time: "07:15",
    label: "REFUEL",
    icon: "🥣",
    duration: "30 min",
    category: "recovery",
    title: "Recovery Nutrition + Shutdown",
    description: "Protein-forward breakfast (eggs, Greek yogurt, or protein shake + fruit).",
    why: "Post-training is a psychological win moment. Protect it from distraction.",
    triathlete: true,
    founder: false,
    recovery: true,
    baseChecks: ["Eat protein-forward breakfast", "No work apps open to avoid early stress", "Eat slowly — no screen time allowed"]
  },
  {
    time: "07:45",
    label: "FOUNDER HOUR",
    icon: "💻",
    duration: "60 min",
    category: "founder",
    title: "Deep Work: App Building",
    description: "Before work starts, spend one focused hour on YOUR app — not the job's projects. Maintain your sovereign builder engine.",
    why: "This is the most important hour of your day. It compounds. In 8 months, you'll have an independent, shipped system.",
    triathlete: false,
    founder: true,
    recovery: false,
    baseChecks: ["Open app project — not work email", "Complete one Pomodoro (25 min)", "Commit at least one line of code"]
  },
  {
    time: "09:00",
    label: "JOB STARTS",
    icon: "💼",
    duration: "480 min",
    category: "work",
    title: "Contained Work Day — Boundaries Strategy",
    description: "Set a firm end time (5:30 PM or 6 PM max). When the new project kicks off, preserve time pockets with ruthless email batching.",
    why: "50-hour weeks are often 40 hours of work + 10 hours of anxiety and context switching. Contain it.",
    triathlete: false,
    founder: false,
    recovery: true,
    baseChecks: ["End time set on calendar (5:30 PM)", "Declined at least one agenda-less meeting", "Ruthlessly batched emails/chats"]
  },
  {
    time: "12:00",
    label: "MIDDAY RESET",
    icon: "🌿",
    duration: "30 min",
    category: "recovery",
    title: "Lunchtime Decompression Walk",
    description: "15-20 minute walk outside. No podcasts. No work calls. Eyes on the horizon.",
    why: "Prevents the 2PM energy crash. Clears decision fatigue. Sunlight in the middle of the day anchors circadian rhythms.",
    triathlete: false,
    founder: false,
    recovery: true,
    baseChecks: ["Step outside for 15-20 min", "No podcasts or calls during walk", "Let mind wander freely without content consumption"]
  },
  {
    time: "17:30",
    label: "HARD STOP",
    icon: "🛑",
    duration: "10 min",
    category: "work",
    title: "Work Shutdown Ritual",
    description: "Close all work apps. Write 3 lines in a work notebook:\n1. What I finished today.\n2. What is remaining for tomorrow.\n3. One win to end on.",
    why: "Burnout partly comes from never actually leaving work. The shutdown ritual is the physical gate locking that world.",
    triathlete: false,
    founder: false,
    recovery: true,
    baseChecks: ["Close all work apps at 5:30 PM sharp", "Write what I finished today", "Write ONE key starting task for tomorrow"]
  },
  {
    time: "18:00",
    label: "LIFE TIME",
    icon: "❤️",
    duration: "150 min",
    category: "recovery",
    title: "Recovery + Human Mode",
    description: "Protect this time fiercely. Options:\n• Cook a real meal (or order premium).\n• Quality social/family engagement.\n• Relaxing mobility walk.",
    why: "You burned out because you had no life outside the project. You are rebuilding a foundation as a complete human.",
    triathlete: false,
    founder: false,
    recovery: true,
    baseChecks: ["No work notifications checked", "Real meal cooked or ordered", "Spend screen-free hour with self or family"]
  },
  {
    time: "20:30",
    label: "NEXT DAY PREP",
    icon: "📝",
    duration: "15 min",
    category: "purpose",
    title: "Tomorrow's ONE Thing",
    description: "Write ONE founder task on a sticky note for tomorrow's 7:45 AM session. Lay out clean athletic training clothes + gear.",
    why: "Reduces decision fatigue in the morning. You wake up already knowing what you're building and have physical frictionless triggers.",
    triathlete: true,
    founder: true,
    recovery: false,
    baseChecks: ["Write tomorrow's ONE founder task on sticky note", "Lay out training gear the night before"]
  },
  {
    time: "21:30",
    label: "WIND DOWN",
    icon: "🌙",
    duration: "30 min",
    category: "recovery",
    title: "Sleep Architecture",
    description: "Phone goes face-down or in another room. Dim lights in your space. 10 minutes light stretching or reading a fiction book.",
    why: "Sleep is when your body builds the athlete, your brain consolidates the learning, and cortisol resets.",
    triathlete: true,
    founder: false,
    recovery: true,
    baseChecks: ["Phone placed in another room or face-down", "Dim all lights in bedroom", "10 minutes of light stretching/reading"]
  }
];

export const DEFAULT_BURNOUT_PLAN: GeneratedPlan = {
  id: "default_burnout",
  userId: "system",
  title: "Burnout Recovery Plan",
  description: "A highly structured lifestyle routine designed for burned-out founders, athletes, and builders to recover durable cognitive stamina.",
  createdAt: 1780000000000,
  blocks: recalibrationSchedule
};
